# Site settings
title: "Brain Chokes USA"
email: 
description: "The Evolution of Choke"
baseurl: "" 
url: "https://brain-usa.com" 
collections:
    - products

colors: "Black|Red|Khaki|Natural"
hunt-constrictions: "Bell|Close Range|Medium Range|Tight Medium|Long Range|Tight Long|Beyond Î§treme|Slug Align"
comp-constrictions: "Competition 1|Competition 2|Competition 3|Competition 4|Competition 5|Competition 6|Competition 7"

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
