# Site settings
title: "Brain Chokes USA"
email: 
description: "The Evolution of Choke"
baseurl: "" 
url: "https://brain-chokes-usa.github.io" 
collections:
    - products

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]